version: '3.9'

services:
  db:
    image: mysql:8.4
    container_name: peaksneaker_db

    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: peaksneaker

    ports:
      - "3306:3306"

    volumes:
      - peaksneaker_mysql_data:/var/lib/mysql

volumes:
  peaksneaker_mysql_data: