# Đổi thành =postgres nếu muốn dùng Postgres
spring.profiles.active=mysql

spring.profiles.include=vnpay,google,ghn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name=duypvtz5w
cloudinary.api-key=169235689553884
cloudinary.api-secret=dBRCesgg94BRy8P5BScYGg0euH8