spring.datasource.url=jdbc:postgresql://localhost:5433/peaksneaker?options=-c%20timezone=UTC
spring.datasource.username=admin
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

cloudinary.cloud-name=duypvtz5w
cloudinary.api-key=169235689553884
cloudinary.api-secret=dBRCesgg94BRy8P5BScYGg0euH8

spring.profiles.include=vnpay,google,ghn